name: protein_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - numpy
  - tqdm
  - matplotlib
  - wandb
  - lightning
  - scipy
  - scikit-learn
  - pip
  - pip:
      - fair-esm

